List<String> titleItems = [
  'Title',
  'Dr',
  'Mrs',
  'Mr',
  'Ms',
];
List<String> incomeItems = [
  "Source of Income",
  "Bussiness/Self-employed",
  "Employement/Salary",
  "Retirement",
  "Housewife",
  "Other Specific",
  "Saving/Investment",
  "Inheritence",
  "Home Remittances",
];
List<String> occupationItems = [
  "Occupation",
  "AGRICULTURIST",
  "ARMED FORCE",
  "BANKER",
  "BUSSINESS/SELF-EMPLOYED",
  "CHARTED ACCOUNTANT",
  "COMMERCIAL PILOT",
  "DEVELOPER",
  "DOCTOR",
  "ENGINEER/TECHNICAN",
  "GOVERNMENT SERVICE",
  "HOUSE WIFE",
  "LAWYER",
  "LECTURER/PROFESSOR/TEACHER",
  "MANAGER",
  "OTHERS",
  "PRIVATE SERVICE",
  "RETIRED",
  "STUDENT",
];
List<String> bracketItems = [
  "Income Bracket",
  "10000-35000",
  "35001-70000",
  "70001-100000",
  "100001-300000",
  "300001-500000",
  "500001-1000000",
  "1000000 & ABOVE",
  "INCOME LESS THAN 10,000",
];

